-- Stage 7: read-only checks after importing the Stage 6 feature dataset.
-- Run sql/01_create_mysql_schema.sql and src/07_load_mysql.py first.
-- These queries do not change the table or create business conclusions.
-- Query 9b requires MySQL 8.0 or later for a CTE and window functions.

USE `dubai_real_estate_intelligence`;

-- 1. Inspect the first 10 imported records. ROW_ID is generated by MySQL.
SELECT *
FROM `dld_transactions_2026_ytd`
ORDER BY `ROW_ID`
LIMIT 10;

-- 2. Count every imported row, including legitimate repeated transactions.
SELECT COUNT(*) AS total_records
FROM `dld_transactions_2026_ytd`;

-- 3. Inspect the date range. MIN and MAX ignore NULL date values.
SELECT
    MIN(`INSTANCE_DATE`) AS earliest_instance_date,
    MAX(`INSTANCE_DATE`) AS latest_instance_date,
    COUNT(*) - COUNT(`INSTANCE_DATE`) AS missing_instance_dates
FROM `dld_transactions_2026_ytd`;

-- 4. List all official transaction groups, including a NULL group if present.
SELECT `GROUP_EN`, COUNT(*) AS record_count
FROM `dld_transactions_2026_ytd`
GROUP BY `GROUP_EN`
ORDER BY record_count DESC, `GROUP_EN`;

-- 5. Compare Sales, Mortgage, and Gifts record counts.
-- The final column keeps any unexpected or missing category visible.
SELECT
    COUNT(CASE WHEN `GROUP_EN` = 'Sales' THEN 1 END) AS sales_records,
    COUNT(CASE WHEN `GROUP_EN` = 'Mortgage' THEN 1 END) AS mortgage_records,
    COUNT(CASE WHEN `GROUP_EN` = 'Gifts' THEN 1 END) AS gifts_records,
    COUNT(CASE
        WHEN `GROUP_EN` NOT IN ('Sales', 'Mortgage', 'Gifts')
             OR `GROUP_EN` IS NULL THEN 1
    END) AS other_or_missing_group_records
FROM `dld_transactions_2026_ytd`;

-- 6. Compare the original Off-Plan and Ready categories.
SELECT
    COUNT(CASE WHEN `IS_OFFPLAN_EN` = 'Off-Plan' THEN 1 END) AS off_plan_records,
    COUNT(CASE WHEN `IS_OFFPLAN_EN` = 'Ready' THEN 1 END) AS ready_records,
    COUNT(CASE
        WHEN `IS_OFFPLAN_EN` NOT IN ('Off-Plan', 'Ready')
             OR `IS_OFFPLAN_EN` IS NULL THEN 1
    END) AS other_or_missing_offplan_records
FROM `dld_transactions_2026_ytd`;

-- 7. Compare Residential and Commercial usage without guessing other usage.
SELECT
    COUNT(CASE WHEN `USAGE_EN` = 'Residential' THEN 1 END) AS residential_records,
    COUNT(CASE WHEN `USAGE_EN` = 'Commercial' THEN 1 END) AS commercial_records,
    COUNT(CASE
        WHEN `USAGE_EN` NOT IN ('Residential', 'Commercial')
             OR `USAGE_EN` IS NULL THEN 1
    END) AS other_or_missing_usage_records
FROM `dld_transactions_2026_ytd`;

-- 8. Inspect the 10 most frequent named areas. Missing names are excluded.
-- This counts records; it does not count distinct properties or buyers.
SELECT `AREA_EN`, COUNT(*) AS record_count
FROM `dld_transactions_2026_ytd`
WHERE `AREA_EN` IS NOT NULL
GROUP BY `AREA_EN`
ORDER BY record_count DESC, `AREA_EN`
LIMIT 10;

-- 9a. Basic average sale price-per-area checks on eligible Sales rows only.
-- AVG ignores NULL values. All populated values, including extremes, remain.
SELECT
    COUNT(`SALE_PRICE_PER_SQM`) AS populated_price_per_sqm_records,
    AVG(`SALE_PRICE_PER_SQM`) AS mean_sale_price_per_sqm,
    COUNT(`SALE_PRICE_PER_SQFT`) AS populated_price_per_sqft_records,
    AVG(`SALE_PRICE_PER_SQFT`) AS mean_sale_price_per_sqft
FROM `dld_transactions_2026_ytd`
WHERE `GROUP_EN` = 'Sales'
  AND `VALID_SALE_PRICE_METRIC` = 1;

-- 9b. Calculate an actual median sale price per sqm (MySQL 8.0 or later).
-- MySQL has no native MEDIAN aggregate. Number non-NULL eligible prices in
-- ascending order, then average the middle one (odd count) or two (even count).
-- ROW_ID breaks ties without removing equal price values or duplicate numbers.
-- An empty set produces NULL, rather than inventing a zero median.
-- Official syntax references:
-- https://dev.mysql.com/doc/refman/8.0/en/window-functions-usage.html
-- https://dev.mysql.com/doc/refman/8.0/en/with.html
WITH ordered_sale_prices AS (
    SELECT
        `SALE_PRICE_PER_SQM`,
        ROW_NUMBER() OVER (
            ORDER BY `SALE_PRICE_PER_SQM`, `ROW_ID`
        ) AS price_position,
        COUNT(*) OVER () AS total_prices
    FROM `dld_transactions_2026_ytd`
    WHERE `GROUP_EN` = 'Sales'
      AND `VALID_SALE_PRICE_METRIC` = 1
      AND `SALE_PRICE_PER_SQM` IS NOT NULL
)
SELECT AVG(`SALE_PRICE_PER_SQM`) AS median_sale_price_per_sqm
FROM ordered_sale_prices
WHERE price_position IN (
    FLOOR((total_prices + 1) / 2),
    FLOOR((total_prices + 2) / 2)
);

-- 10. Inspect the top 10 named areas by Sales record count.
-- Repeated TRANSACTION_NUMBER values remain legitimate separate records.
SELECT `AREA_EN`, COUNT(*) AS sales_record_count
FROM `dld_transactions_2026_ytd`
WHERE `GROUP_EN` = 'Sales'
  AND `AREA_EN` IS NOT NULL
GROUP BY `AREA_EN`
ORDER BY sales_record_count DESC, `AREA_EN`
LIMIT 10;

-- 11. Check the number of records with no sale price per sqm.
-- Non-sale records are expected to have a NULL sale price metric.
SELECT COUNT(*) AS null_sale_price_per_sqm_records
FROM `dld_transactions_2026_ytd`
WHERE `SALE_PRICE_PER_SQM` IS NULL;

-- 12. Count unique, non-NULL transaction numbers without deleting any rows.
-- Distinct transaction numbers can be fewer than records for valid reasons.
SELECT
    COUNT(DISTINCT `TRANSACTION_NUMBER`) AS unique_transaction_numbers,
    COUNT(*) - COUNT(`TRANSACTION_NUMBER`) AS missing_transaction_numbers
FROM `dld_transactions_2026_ytd`;
